# Generated by Django 4.1.5 on 2023-01-05 08:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import myapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('memo', models.CharField(max_length=100)),
                ('budget', models.DecimalField(decimal_places=0, max_digits=9)),
                ('is_delete', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_books', to=settings.AUTH_USER_MODEL, verbose_name='유저')),
            ],
            options={
                'db_table': 'account_books',
            },
            bases=(models.Model, myapp.models.IsDelete),
        ),
        migrations.CreateModel(
            name='AccountDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('price', models.DecimalField(decimal_places=0, max_digits=9)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('account_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_details', to='myapp.accountbook', verbose_name='가계부')),
            ],
            options={
                'db_table': 'account_detail',
            },
            bases=(models.Model, myapp.models.IsDelete),
        ),
    ]
